language: node_js

notifications:
  email: false

node_js:
  - '6.9'

sudo: false

cache:
  directories:
    - node_modules

git:
  submodules: false

before_install:
  - npm install -g grunt-cli
  - grunt --version

script:
  - npm start
