version: "{build}"

init:
  - git config --global core.autocrlf true

environment:
  nodejs_version: 6.9.1

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --force

build: off

test_script:
  - node --version
  - npm --version
  - npm start

matrix:
  fast_finish: true

cache:
  - C:\Users\appveyor\AppData\Roaming\npm-cache -> package.json
  - node_modules -> package.json
